# Generated by Django 5.0.7 on 2024-08-07 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='users', to='base.product'),
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.ManyToManyField(blank=True, related_name='products', to='base.type'),
        ),
    ]
