# Generated by Django 5.0.7 on 2024-08-12 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_image_artist_image_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='artist',
            field=models.CharField(max_length=255),
        ),
    ]
